export const actionTypes = {
    EMPLOYEE_UPDATE_ID:"EMPLOYEE_UPDATE_ID",
    GET_EMPLOYEES_DATA:"GET_EMPLOYEES_DATA",
    CREATE_NEW_EMPLOYEE: "CREATE_NEW_EMPLOYEE",
    UPDATE_NEW_EMPLOYEE:"UPDATE_NEW_EMPLOYEE",
    RESPONSE_MESSAGE:"RESPONSE_MESSAGE"
}